// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[...slug]" | "/approvals" | "/dashboard" | "/exec/users" | "/inventory/stock/adjustment" | "/inventory/stock/management" | "/login" | "/manufacturing" | "/manufacturing/boms" | "/manufacturing/boms/new" | "/manufacturing/genealogy" | "/manufacturing/issues" | "/manufacturing/issues/new" | "/manufacturing/orders" | "/manufacturing/orders/new" | "/manufacturing/qc" | "/manufacturing/qc/new" | "/manufacturing/receipts" | "/manufacturing/receipts/new" | "/masters/parties" | "/masters/products" | "/purchase/debit-notes" | "/purchase/debit-notes/new" | "/purchase/orders" | "/purchase/orders/new" | "/purchase/register" | "/purchase/register/new" | "/register/ac-ledger" | "/register/reports" | "/returns/purchase" | "/returns/purchase/new" | "/returns/report" | "/returns/sales" | "/returns/sales/new" | "/sales/bills" | "/sales/bills/new" | "/sales/credit-notes" | "/sales/credit-notes/new" | "/sales/orders" | "/sales/orders/new" | "/sales/register" | "/sales/register/new" | "/settings"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[...slug]": { "slug": string[]; }
  "/approvals": {}
  "/dashboard": {}
  "/exec/users": {}
  "/inventory/stock/adjustment": {}
  "/inventory/stock/management": {}
  "/login": {}
  "/manufacturing": {}
  "/manufacturing/boms": {}
  "/manufacturing/boms/new": {}
  "/manufacturing/genealogy": {}
  "/manufacturing/issues": {}
  "/manufacturing/issues/new": {}
  "/manufacturing/orders": {}
  "/manufacturing/orders/new": {}
  "/manufacturing/qc": {}
  "/manufacturing/qc/new": {}
  "/manufacturing/receipts": {}
  "/manufacturing/receipts/new": {}
  "/masters/parties": {}
  "/masters/products": {}
  "/purchase/debit-notes": {}
  "/purchase/debit-notes/new": {}
  "/purchase/orders": {}
  "/purchase/orders/new": {}
  "/purchase/register": {}
  "/purchase/register/new": {}
  "/register/ac-ledger": {}
  "/register/reports": {}
  "/returns/purchase": {}
  "/returns/purchase/new": {}
  "/returns/report": {}
  "/returns/sales": {}
  "/returns/sales/new": {}
  "/sales/bills": {}
  "/sales/bills/new": {}
  "/sales/credit-notes": {}
  "/sales/credit-notes/new": {}
  "/sales/orders": {}
  "/sales/orders/new": {}
  "/sales/register": {}
  "/sales/register/new": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
