// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(app)/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[...slug]">> = Specific
  const handler = {} as typeof import("../../app/(app)/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals">> = Specific
  const handler = {} as typeof import("../../app/(app)/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/exec/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/exec/users">> = Specific
  const handler = {} as typeof import("../../app/(app)/exec/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/inventory/stock/adjustment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/stock/adjustment">> = Specific
  const handler = {} as typeof import("../../app/(app)/inventory/stock/adjustment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/inventory/stock/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/stock/management">> = Specific
  const handler = {} as typeof import("../../app/(app)/inventory/stock/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/boms/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/boms/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/boms/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/boms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/boms">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/boms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/genealogy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/genealogy">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/genealogy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/issues/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/issues/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/issues/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/issues">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/orders/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/orders">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/qc/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/qc/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/qc/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/qc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/qc">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/qc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/receipts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/receipts/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/receipts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/manufacturing/receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturing/receipts">> = Specific
  const handler = {} as typeof import("../../app/(app)/manufacturing/receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/masters/parties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/parties">> = Specific
  const handler = {} as typeof import("../../app/(app)/masters/parties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/masters/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/masters/products">> = Specific
  const handler = {} as typeof import("../../app/(app)/masters/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/debit-notes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/debit-notes/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/debit-notes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/debit-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/debit-notes">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/debit-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/orders/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/orders">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/register/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/register/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/register/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/purchase/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/register">> = Specific
  const handler = {} as typeof import("../../app/(app)/purchase/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/register/ac-ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/ac-ledger">> = Specific
  const handler = {} as typeof import("../../app/(app)/register/ac-ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/register/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register/reports">> = Specific
  const handler = {} as typeof import("../../app/(app)/register/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/returns/purchase/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns/purchase/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/returns/purchase/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/returns/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns/purchase">> = Specific
  const handler = {} as typeof import("../../app/(app)/returns/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/returns/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns/report">> = Specific
  const handler = {} as typeof import("../../app/(app)/returns/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/returns/sales/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns/sales/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/returns/sales/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/returns/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/returns/sales">> = Specific
  const handler = {} as typeof import("../../app/(app)/returns/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/bills/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/bills/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/bills/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/bills">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/credit-notes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/credit-notes/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/credit-notes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/credit-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/credit-notes">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/credit-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/register/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/register/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/register/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/sales/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/register">> = Specific
  const handler = {} as typeof import("../../app/(app)/sales/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
